language: erlang
otp_release:
  - 17.0
  - 17.1
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir
  - git checkout tags/v1.0.0-rc1
  - make
  - cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - MIX_ENV=test mix do deps.get
script:
  - mix test
after_success:
  - MIX_ENV=test mix coveralls.travis
