language: erlang
otp_release:
  - 17.0
  - 17.1
before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.0.0-rc1.zip
  - unzip -d elixir v1.0.0-rc1.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - MIX_ENV=test mix do deps.get
script:
  - mix test
after_success:
  - mix coveralls.travis
